### ISSUE TITLE
Update the value sets according to the v1.5 of the eHealth Network Guidelines

### ISSUE THREAD

**Issue by skounis** [ehn-dcc-development/ehn-dcc-valuesets#30]
Key changes:
1. New vaccines:
    a. Abdala, used in Vietnam
    b. WIBP-CorV, used in Vietnam
2. New manufacturer:
    a. Center for Genetic Engineering and Biotechnology (CIGB) for Abdala
    b. Sinopharm - Wuhan Institute of Biological Products for WIBP-CorV

## Guidelines document
The document for the `v1.5` is adopted and published

* https://ec.europa.eu/health/ehealth/covid-19_en
* https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-value-sets_en.pdf

**Comment by dslmeinte** [comment]
Isn't this according to v1.**5**?

**Comment by skounis** [comment]
Correct. Just changed the title.

**Comment by skounis** [comment]
@dslmeinte @kruzikh The `v1.5` is published. I updated the description adding the links.

**Comment by dslmeinte** [comment]
Done per PR #31 (and PR #32).
