### ISSUE TITLE
Grant Daniel Karlsson reviewer rights

### ISSUE THREAD

**Issue by dslmeinte** [ehn-dcc-development/ehn-dcc-valuesets#47]
I recommend to add Daniel Karlsson into the reviewers team.

_Originally posted by @kruzikh in https://github.com/ehn-dcc-development/ehn-dcc-valuesets/issues/46#issuecomment-1023138015_

Handle: `danka74`

**Comment by dslmeinte** [comment]
@skounis @ryanbnl Agree to invite Daniel as an outside collaborator? Also agree to give him reviewer rights?

**Comment by ryanbnl** [comment]
Is he working for one of the MS or EC?

-- 
Ryan

**Comment by kruzikh** [comment]
Daniel is a member of the semantic subgroup.

**Comment by ryanbnl** [comment]
Then it's a no brainer, of course he can be added :)

-- 
Ryan

**Comment by dslmeinte** [comment]
I invited `danka74` with “Triage” right which should suffice for reviewing. We can grant more rights at any time.
